vscode:
  extensions:
    - esbenp.prettier-vscode@3.20.0:37/f4uBlE287wUjENFq1aA==
    - ritwickdey.LiveServer@5.6.1:wV4LBkq6Z5s1xwf2HrB+cw==
    - eamodio.gitlens@10.2.1:e0IYyp0efFqVsrZwsIe8CA==
    - castwide.solargraph@0.21.1:kJz6aC6XZbI/EeYHUPNCmQ==
    - bung87.rails@0.16.2:HZRuRl8OsagizSxxVwpESw==